[rust]
cmd = "rust-analyzer"
extensions = ["rs"]

[typescript]
cmd = "vtsls --stdio"
extensions = ["ts", "tsx"]

[python]
cmd = "basedpyright-langserver --stdio"
extensions = ["py"]

[go]
cmd = "gopls"
extensions = ["go"]

[c]
cmd = "clangd"
extensions = ["c", "h"]
